attempt #1 at getting this to work

diff --git a/libexec/erlenv-rehash b/libexec/erlenv-rehash
--- a/libexec/erlenv-rehash
+++ b/libexec/erlenv-rehash
@@ -1,51 +1,51 @@
 #!/usr/bin/env bash
 set -e
-[ -n "$RBENV_DEBUG" ] && set -x
+[ -n "$ERLENV_DEBUG" ] && set -x
 
-SHIM_PATH="${RBENV_ROOT}/shims"
-PROTOTYPE_SHIM_PATH="${SHIM_PATH}/.rbenv-shim"
+SHIM_PATH="${ERLENV_ROOT}/shims"
+PROTOTYPE_SHIM_PATH="${SHIM_PATH}/.erlenv-shim"
 
-# Create the shims directory if it doesn't already exist.
+# create the shims directory if it doesn't already exist
 mkdir -p "$SHIM_PATH"
 
-# Ensure only one instance of rbenv-rehash is running at a time by
+# ensure only one instance of erlenv-rehash is running at a time by
 # setting the shell's `noclobber` option and attempting to write to
-# the prototype shim file. If the file already exists, print a warning
-# to stderr and exit with a non-zero status.
+# the prototype shim file. if the file already exists, print a warning
+# to stderr and exit with a non-zero status
 set -o noclobber
 { echo > "$PROTOTYPE_SHIM_PATH"
 } 2>/dev/null ||
-{ echo "rbenv: cannot rehash: $PROTOTYPE_SHIM_PATH exists"
+{ echo "erlenv: cannot rehash: $PROTOTYPE_SHIM_PATH exists"
   exit 1
 } >&2
 set +o noclobber
 
-# If we were able to obtain a lock, register a trap to clean up the
-# prototype shim when the process exits.
+# if we were able to obtain a lock, register a trap to clean up the
+# prototype shim when the process exits
 trap remove_prototype_shim EXIT
 
 remove_prototype_shim() {
   rm -f "$PROTOTYPE_SHIM_PATH"
 }
 
-# The prototype shim file is a script that re-execs itself, passing
-# its filename and any arguments to `rbenv exec`. This file is
-# hard-linked for every binary and then removed. The linking technique
+# the prototype shim file is a script that re-execs itself, passing
+# its filename and any arguments to `erlenv exec`. this file is
+# hard-linked for every binary and then removed. the linking technique
 # is fast, uses less disk space than unique files, and also serves as
-# a locking mechanism.
+# a locking mechanism
 create_prototype_shim() {
   cat > "$PROTOTYPE_SHIM_PATH" <<SH
 #!/usr/bin/env bash
 set -e
-export RBENV_ROOT="$RBENV_ROOT"
-exec rbenv exec "\${0##*/}" "\$@"
+export ERLENV_ROOT="$ERLENV_ROOT"
+exec erlenv exec "\${0##*/}" "\$@"
 SH
   chmod +x "$PROTOTYPE_SHIM_PATH"
 }
 
-# The basename of each argument passed to `make_shims` will be
-# registered for installation as a shim. In this way, plugins may call
-# `make_shims` with a glob to register many shims at once.
+# the basename of each argument passed to `make_shims` will be
+# registered for installation as a shim. in this way, plugins may call
+# `make_shims` with a glob to register many shims at once
 make_shims() {
   local shims="$@"
 
@@ -55,14 +55,14 @@ make_shims() {
   done
 }
 
-# Create an empty array for the list of registered shims.
+# create an empty array for the list of registered shims
 registered_shims=()
 
-# We will keep track of shims registered for installation with the
+# we will keep track of shims registered for installation with the
 # global `reigstered_shims` array and with a global variable for each
-# shim. The array will let us iterate over all registered shims. The
+# shim. the array will let us iterate over all registered shims. the
 # global variables will let us quickly check whether a shim with the
-# given name has been registered or not.
+# given name has been registered or not
 register_shim() {
   local shim="$@"
   local var="$(shim_variable_name "$shim")"
@@ -73,11 +73,11 @@ register_shim() {
   fi
 }
 
-# To compute the global variable name for a given shim we must first
-# escape any non-alphanumeric characters. If the shim name is
+# to compute the global variable name for a given shim we must first
+# escape any non-alphanumeric characters. if the shim name is
 # alphanumeric (including a hyphen or underscore) we can take a
-# shorter path. Otherwise, we must iterate over each character and
-# escape the non-alphanumeric ones using `printf`.
+# shorter path. otherwise, we must iterate over each character and
+# escape the non-alphanumeric ones using `printf`
 shim_variable_name() {
   local shim="$1"
   local result="_shim_"
@@ -103,19 +103,19 @@ shim_variable_name() {
   echo "$result"
 }
 
-# To install all the registered shims, we iterate over the
+# to install all the registered shims, we iterate over the
 # `registered_shims` array and create a link if one does not already
-# exist.
+# exist
 install_registered_shims() {
   for shim in "${registered_shims[@]}"; do
     [ -e "$shim" ] || ln -f "$PROTOTYPE_SHIM_PATH" "$shim"
   done
 }
 
-# Once the registered shims have been installed, we make a second pass
-# over the contents of the shims directory. Any file that is present
+# once the registered shims have been installed, we make a second pass
+# over the contents of the shims directory. any file that is present
 # in the directory but has not been registered as a shim should be
-# removed.
+# removed
 remove_stale_shims() {
   local var
   for shim in *; do
@@ -127,24 +127,24 @@ remove_stale_shims() {
 }
 
 
-# Change to the shims directory.
+# change to the shims directory
 cd "$SHIM_PATH"
 
-# Create the prototype shim, then register shims for all known binaries.
+# create the prototype shim, then register shims for all known binaries
 create_prototype_shim
 shopt -s nullglob
-make_shims ../versions/*/bin/*
+make_shims ../releases/*/bin/*
 
-# Restore the previous working directory.
+# restore the previous working directory
 cd "$OLDPWD"
 
-# Allow plugins to register shims.
-for script in $(rbenv-hooks rehash); do
+# allow plugins to register shims
+for script in $(erlenv-hooks rehash); do
   source "$script"
 done
 
-# Change back to the shims directory to install the registered shims
-# and remove stale shims.
+# change back to the shims directory to install the registered shims
+# and remove stale shims
 cd "$SHIM_PATH"
 install_registered_shims
 remove_stale_shims
