search/replace all rubyisms for erlangisms

diff --git a/libexec/erlenv b/libexec/erlenv
--- a/libexec/erlenv
+++ b/libexec/erlenv
@@ -3,11 +3,11 @@ set -e
 export -n CDPATH
 
 if [ "$1" = "--debug" ]; then
-  export RBENV_DEBUG=1
+  export ERLENV_DEBUG=1
   shift
 fi
 
-if [ -n "$RBENV_DEBUG" ]; then
+if [ -n "$ERLENV_DEBUG" ]; then
   export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
   set -x
 fi
@@ -30,39 +30,39 @@ abs_dirname() {
   cd "$cwd"
 }
 
-if [ -z "${RBENV_ROOT}" ]; then
-  RBENV_ROOT="${HOME}/.rbenv"
+if [ -z "${ERLENV_ROOT}" ]; then
+  ERLENV_ROOT="${HOME}/.erlenv"
 else
-  RBENV_ROOT="${RBENV_ROOT%/}"
+  ERLENV_ROOT="${ERLENV_ROOT%/}"
 fi
-export RBENV_ROOT
+export ERLENV_ROOT
 
-if [ -z "${RBENV_DIR}" ]; then
-  RBENV_DIR="$(pwd)"
+if [ -z "${ERLENV_DIR}" ]; then
+  ERLENV_DIR="$(pwd)"
 else
-  cd "$RBENV_DIR" 2>/dev/null || {
-    echo "rbenv: cannot change working directory to \`$RBENV_DIR'"
+  cd "$ERLENV_DIR" 2>/dev/null || {
+    echo "erlenv: cannot change working directory to \`$ERLENV_DIR'"
     exit 1
   } >&2
-  RBENV_DIR="$(pwd)"
+  ERLENV_DIR="$(pwd)"
   cd "$OLDPWD"
 fi
-export RBENV_DIR
+export ERLENV_DIR
 
 
 shopt -s nullglob
 
 bin_path="$(abs_dirname "$0")"
-for plugin_bin in "${RBENV_ROOT}/plugins/"*/bin; do
+for plugin_bin in "${ERLENV_ROOT}/plugins/"*/bin; do
   bin_path="${bin_path}:${plugin_bin}"
 done
 export PATH="${bin_path}:${PATH}"
 
-hook_path="${RBENV_HOOK_PATH}:${RBENV_ROOT}/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks"
-for plugin_hook in "${RBENV_ROOT}/plugins/"*/etc/rbenv.d; do
+hook_path="${ERLENV_HOOK_PATH}:${ERLENV_ROOT}/erlenv.d:/usr/local/etc/erlenv.d:/etc/erlenv.d:/usr/lib/erlenv/hooks"
+for plugin_hook in "${ERLENV_ROOT}/plugins/"*/etc/erlenv.d; do
   hook_path="${hook_path}:${plugin_hook}"
 done
-export RBENV_HOOK_PATH="$hook_path"
+export ERLENV_HOOK_PATH="$hook_path"
 
 shopt -u nullglob
 
@@ -70,15 +70,15 @@ shopt -u nullglob
 command="$1"
 case "$command" in
 "" | "-h" | "--help" )
-  echo -e "$(rbenv---version)\n$(rbenv-help)" >&2
+  echo -e "$(erlenv-version)\n$(erlenv-help)" >&2
   ;;
 "-v" )
-  exec rbenv---version
+  exec erlenv-version
   ;;
 * )
-  command_path="$(command -v "rbenv-$command" || true)"
+  command_path="$(command -v "erlenv-$command" || true)"
   if [ -z "$command_path" ]; then
-    echo "rbenv: no such command \`$command'" >&2
+    echo "erlenv: no such command \`$command'" >&2
     exit 1
   fi
 
