fix tests

diff --git a/libexec/erlenv-prefix b/libexec/erlenv-prefix
--- a/libexec/erlenv-prefix
+++ b/libexec/erlenv-prefix
@@ -1,41 +1,41 @@
 #!/usr/bin/env bash
-# Summary: Display prefix for a Ruby version
-# Usage: rbenv prefix [<version>]
+# Summary: Display prefix for an erlang release
+# Usage: erlenv prefix [<release>]
 #
-# Displays the directory where a Ruby version is installed. If no
-# version is given, `rbenv prefix' displays the location of the
-# currently selected version.
+# Displays the directory where an erlang release is installed. If no
+# version is given, `erlenv prefix' displays the location of the
+# currently selected release
 
 set -e
-[ -n "$RBENV_DEBUG" ] && set -x
+[ -n "$ERLENV_DEBUG" ] && set -x
 
-# Provide rbenv completions
+# Provide erlenv completions
 if [ "$1" = "--complete" ]; then
   echo system
-  exec rbenv-versions --bare
+  exec erlenv-releases --bare
 fi
 
 if [ -n "$1" ]; then
-  export RBENV_VERSION="$1"
-elif [ -z "$RBENV_VERSION" ]; then
-  RBENV_VERSION="$(rbenv-version-name)"
+  export ERLENV_RELEASE="$1"
+elif [ -z "$ERLENV_RELEASE" ]; then
+  ERLENV_RELEASE="$(erlenv-release-name)"
 fi
 
-if [ "$RBENV_VERSION" = "system" ]; then
-  if RUBY_PATH="$(rbenv-which ruby 2>/dev/null)"; then
-    RUBY_PATH="${RUBY_PATH%/*}"
-    echo "${RUBY_PATH%/bin}"
+if [ "$ERLENV_RELEASE" = "system" ]; then
+  if ERLANG_PATH="$(erlenv-which erl 2>/dev/null)"; then
+    ERLANG_PATH="${ERLANG_PATH%/*}"
+    echo "${ERLANG_PATH%/bin}"
     exit
   else
-    echo "rbenv: system version not found in PATH" >&2
+    echo "erlenv: system version not found in PATH" >&2
     exit 1
   fi
 fi
 
-RBENV_PREFIX_PATH="${RBENV_ROOT}/versions/${RBENV_VERSION}"
-if [ ! -d "$RBENV_PREFIX_PATH" ]; then
-  echo "rbenv: version \`${RBENV_VERSION}' not installed" >&2
+ERLENV_PREFIX_PATH="${ERLENV_ROOT}/releases/${ERLENV_RELEASE}"
+if [ ! -d "$ERLENV_PREFIX_PATH" ]; then
+  echo "erlenv: release \`${ERLENV_RELEASE}' not installed" >&2
   exit 1
 fi
 
-echo "$RBENV_PREFIX_PATH"
+echo "$ERLENV_PREFIX_PATH"
