last bit of cleanup

diff --git a/libexec/erlenv b/libexec/erlenv
--- a/libexec/erlenv
+++ b/libexec/erlenv
@@ -14,7 +14,7 @@ fi
 
 READLINK=$(type -p greadlink readlink | head -1)
 if [ -z "$READLINK" ]; then
-  echo "rbenv: cannot find readlink - are you missing GNU coreutils?" >&2
+  echo "erlenv: cannot find readlink - are you missing GNU coreutils?" >&2
   exit 1
 fi
 
